// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A autonomous reasoning AI agent.
 *
 * - autonomousReasoning - A function that handles the autonomous reasoning process.
 * - AutonomousReasoningInput - The input type for the autonomousReasoning function.
 * - AutonomousReasoningOutput - The return type for the autonomousReasoning function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutonomousReasoningInputSchema = z.object({
  context: z.string().describe('The current context of the conversation, including past messages.'),
  userInput: z.string().describe('The user input to analyze and respond to.'),
});
export type AutonomousReasoningInput = z.infer<typeof AutonomousReasoningInputSchema>;

const AutonomousReasoningOutputSchema = z.object({
  responseToUser: z.string().describe('A direct, conversational reply to the user based on the context and their input.'),
  reasoning: z.string().describe('The reasoning behind the generated response.'),
});
export type AutonomousReasoningOutput = z.infer<typeof AutonomousReasoningOutputSchema>;

export async function autonomousReasoning(input: AutonomousReasoningInput): Promise<AutonomousReasoningOutput> {
  return autonomousReasoningFlow(input);
}

const prompt = ai.definePrompt({
  name: 'autonomousReasoningPrompt',
  input: {schema: AutonomousReasoningInputSchema},
  output: {schema: AutonomousReasoningOutputSchema},
  prompt: `You are an AI assistant. Your role is to analyze the context of a conversation and the user's input to generate a helpful and relevant response.

Conversation Context:
{{{context}}}

User's Latest Input:
{{{userInput}}}

Based on the full conversation context and the user's latest input, generate a direct conversational "responseToUser". Also, provide a brief "reasoning" for why you chose that response.

Output in JSON format:
{
  "responseToUser": "The conversational reply to send to the user.",
  "reasoning": "The reasoning behind the chosen response."
}
`,
});

const autonomousReasoningFlow = ai.defineFlow(
  {
    name: 'autonomousReasoningFlow',
    inputSchema: AutonomousReasoningInputSchema,
    outputSchema: AutonomousReasoningOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
