
import { z } from 'zod';

// Zod Schema for KnowledgeItem
export const KnowledgeItemSchema = z.object({
  id: z.string(),
  fileName: z.string(),
  uploadedAt: z.string(), // ISO date string
  summary: z.string().optional(),
  keywords: z.array(z.string()).optional(),
});
export type KnowledgeItem = z.infer<typeof KnowledgeItemSchema>;

// Zod Schemas for Flow Definition
export const FlowNodeSchema = z.object({
  id: z.string(),
  type: z.enum([
    'start', 
    'sendMessage', 
    'getUserInput', 
    'callLLM', 
    'condition', 
    'apiCall', // Used for HTTP Request
    'end',
    'action',      // New
    'code',        // New
    'qnaLookup',   // New
    'wait',        // New
    'transition',  // New
    'agentSkill'   // New
  ]),
  position: z.object({ x: z.number(), y: z.number() }).optional(),
  
  // sendMessage
  message: z.string().optional(),
  
  // getUserInput (Ask Question)
  prompt: z.string().optional(), 
  variableName: z.string().optional(), 
  inputType: z.string().optional().describe("e.g., text, number, email, choice, date"),
  validationRules: z.string().optional().describe("e.g., regex, ranges"),

  // callLLM
  llmPrompt: z.string().optional(), 
  outputVariable: z.string().optional(), 
  useKnowledge: z.boolean().optional(),
  
  // condition
  conditionVariable: z.string().optional(), 
  useLLMForDecision: z.boolean().optional().describe("If true, uses an LLM to match conditionVariable's value against edge conditions."),
  conditionExpressions: z.array(z.string()).optional().describe("List of JS/Nunjucks expressions for condition node"),


  // apiCall (HTTP Request)
  apiUrl: z.string().optional(),
  apiMethod: z.enum(['GET', 'POST', 'PUT', 'DELETE', 'PATCH']).optional(), 
  apiHeaders: z.record(z.string()).optional(),
  apiBodyVariable: z.string().optional().describe("Variable from context for request body"),
  apiTimeout: z.number().optional(),
  apiRetryAttempts: z.number().optional(),
  apiOutputVariable: z.string().optional(), 

  // end
  endOutputVariable: z.string().optional().describe("Variable from context to output from the flow"),

  // action
  actionName: z.string().optional(),
  actionInputArgs: z.record(z.any()).optional(),
  actionOutputVarMap: z.record(z.string()).optional(),

  // code
  codeScript: z.string().optional(),
  codeReturnVarMap: z.record(z.string()).optional(),

  // qnaLookup
  qnaKnowledgeBaseId: z.string().optional(),
  qnaThreshold: z.number().optional(),
  qnaFallbackText: z.string().optional(),

  // wait
  waitDurationMs: z.number().optional(),

  // transition
  transitionTargetFlowId: z.string().optional(),
  transitionTargetNodeId: z.string().optional(),
  transitionVariablesToPass: z.record(z.any()).optional(),

  // agentSkill
  agentSkillId: z.string().optional(),
  agentSkillsList: z.array(z.string()).optional(),
  agentContextWindow: z.number().optional(),

});
export type FlowNode = z.infer<typeof FlowNodeSchema>;

export const FlowEdgeSchema = z.object({
  id: z.string(),
  source: z.string(), // source node id
  target: z.string(), // target node id
  label: z.string().optional(), // Visual label for the edge (e.g., for conditions or error paths)
  condition: z.string().optional(), // Value for conditional branching or descriptive category for LLM. Empty/absent for default/unconditional.
  edgeType: z.enum(['success', 'error', 'invalid', 'default', 'found', 'notFound']).optional().describe("Semantic type for edge, e.g. for HTTP error paths")
});
export type FlowEdge = z.infer<typeof FlowEdgeSchema>;

export const AgentFlowDefinitionSchema = z.object({
  flowId: z.string(),
  name: z.string(),
  description: z.string(),
  nodes: z.array(FlowNodeSchema),
  edges: z.array(FlowEdgeSchema),
});
export type AgentFlowDefinition = z.infer<typeof AgentFlowDefinitionSchema>;

// Zod Schema for Flow Context
export const FlowContextSchema = z.record(z.any()).describe("Holds variables like userName, llmResponse etc. Also includes conversationHistory and potentially other dynamic state.");
export type FlowContext = z.infer<typeof FlowContextSchema>;


// Existing Agent and other types
export interface Agent {
  id: string;
  name: string;
  description: string; // User-provided description
  role?: string; // User-provided role for creation
  personality?: string; // User-provided personality for creation
  generatedName?: string; // Name generated by AI
  generatedPersona?: string; // Persona generated by AI
  generatedGreeting?: string; // Greeting generated by AI
  createdAt: string;
  knowledgeItems?: KnowledgeItem[]; // Uses the Zod-inferred type
  flow?: AgentFlowDefinition; // Each agent can have one flow
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'agent';
  text: string;
  timestamp: number;
  intent?: string;
  entities?: Record<string, string>;
  reasoning?: string; // From autonomous reasoning
  flowNodeId?: string; // ID of the flow node that generated this message
  flowContext?: FlowContext; // Context at the time of this message (for debugging or state)
}

