export interface Agent {
  id: string;
  name: string;
  description: string; // User-provided description
  role?: string; // User-provided role for creation
  personality?: string; // User-provided personality for creation
  generatedName?: string; // Name generated by AI
  generatedPersona?: string; // Persona generated by AI
  generatedGreeting?: string; // Greeting generated by AI
  createdAt: string;
}

export interface KnowledgeItem {
  id: string;
  fileName: string;
  uploadedAt: string;
  summary?: string;
  keywords?: string[];
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'agent';
  text: string;
  timestamp: number;
  intent?: string;
  entities?: Record<string, string>;
  reasoning?: string;
}
